services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Services\RatesUpdater:
        arguments:
            - !tagged_iterator app.rates_provider

    App\Providers\FakeRatesProvider:
        arguments:
            $url: ''
            $base: ''
        tags: [ 'app.rates_provider' ]
